### ISSUE TITLE
Milestones for the first release

### ISSUE THREAD

**Issue by PuneetPunamiya** [openshift-pipelines/manual-approval-gate#126]
- [ ] Support for multiple users
     - [ ] Handle when approvalRequired is not given
- [ ] Adds auth by configuring webhook controller
- [ ] Handle deletion of approvaltasks when customrun is deleted
- [ ] Support for message while approving the approvaltask
- [ ] Handle the scenario when approvals list is not given but approvalsRequired is given (as of today oc edit works for this, oc patch won't work) (future tkn should add this)
- [ ] Improve logs 
   - [ ]  compute the hash of Approvaltask spec and store as an annotation, 
	 in further reconciliation we compute hash of ApprovalTask spec and check with
	 annotation, if they are same then we skip updating the object
	 otherwise we update approvaltask state based on the input

**Comment by zijiwork** [comment]
Does it work on kubernetes1.26 tekton v0.40.0 version?
